package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * HostSummaryByFileIo generated by hbm2java
 */
public class HostSummaryByFileIo implements java.io.Serializable {

	private HostSummaryByFileIoId id;

	public HostSummaryByFileIo() {
	}

	public HostSummaryByFileIo(HostSummaryByFileIoId id) {
		this.id = id;
	}

	public HostSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoId id) {
		this.id = id;
	}

}
