package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * HostSummaryByStages generated by hbm2java
 */
public class HostSummaryByStages implements java.io.Serializable {

	private HostSummaryByStagesId id;

	public HostSummaryByStages() {
	}

	public HostSummaryByStages(HostSummaryByStagesId id) {
		this.id = id;
	}

	public HostSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStagesId id) {
		this.id = id;
	}

}
