package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * InnodbLockWaits generated by hbm2java
 */
public class InnodbLockWaits implements java.io.Serializable {

	private InnodbLockWaitsId id;

	public InnodbLockWaits() {
	}

	public InnodbLockWaits(InnodbLockWaitsId id) {
		this.id = id;
	}

	public InnodbLockWaitsId getId() {
		return this.id;
	}

	public void setId(InnodbLockWaitsId id) {
		this.id = id;
	}

}
