package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * InnodbBufferStatsByTable generated by hbm2java
 */
public class InnodbBufferStatsByTable implements java.io.Serializable {

	private InnodbBufferStatsByTableId id;

	public InnodbBufferStatsByTable() {
	}

	public InnodbBufferStatsByTable(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

	public InnodbBufferStatsByTableId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

}
