package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * IoGlobalByFileByBytes generated by hbm2java
 */
public class IoGlobalByFileByBytes implements java.io.Serializable {

	private IoGlobalByFileByBytesId id;

	public IoGlobalByFileByBytes() {
	}

	public IoGlobalByFileByBytes(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

	public IoGlobalByFileByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

}
