package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * LatestFileIo generated by hbm2java
 */
public class LatestFileIo implements java.io.Serializable {

	private LatestFileIoId id;

	public LatestFileIo() {
	}

	public LatestFileIo(LatestFileIoId id) {
		this.id = id;
	}

	public LatestFileIoId getId() {
		return this.id;
	}

	public void setId(LatestFileIoId id) {
		this.id = id;
	}

}
