package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * MemoryByHostByCurrentBytes generated by hbm2java
 */
public class MemoryByHostByCurrentBytes implements java.io.Serializable {

	private MemoryByHostByCurrentBytesId id;

	public MemoryByHostByCurrentBytes() {
	}

	public MemoryByHostByCurrentBytes(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByHostByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

}
