package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * Processlist generated by hbm2java
 */
public class Processlist implements java.io.Serializable {

	private ProcesslistId id;

	public Processlist() {
	}

	public Processlist(ProcesslistId id) {
		this.id = id;
	}

	public ProcesslistId getId() {
		return this.id;
	}

	public void setId(ProcesslistId id) {
		this.id = id;
	}

}
