package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * PsCheckLostInstrumentation generated by hbm2java
 */
public class PsCheckLostInstrumentation implements java.io.Serializable {

	private PsCheckLostInstrumentationId id;

	public PsCheckLostInstrumentation() {
	}

	public PsCheckLostInstrumentation(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

	public PsCheckLostInstrumentationId getId() {
		return this.id;
	}

	public void setId(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

}
