package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * SchemaTableStatistics generated by hbm2java
 */
public class SchemaTableStatistics implements java.io.Serializable {

	private SchemaTableStatisticsId id;

	public SchemaTableStatistics() {
	}

	public SchemaTableStatistics(SchemaTableStatisticsId id) {
		this.id = id;
	}

	public SchemaTableStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsId id) {
		this.id = id;
	}

}
