package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * SchemaTableStatisticsWithBuffer generated by hbm2java
 */
public class SchemaTableStatisticsWithBuffer implements java.io.Serializable {

	private SchemaTableStatisticsWithBufferId id;

	public SchemaTableStatisticsWithBuffer() {
	}

	public SchemaTableStatisticsWithBuffer(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

	public SchemaTableStatisticsWithBufferId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

}
