package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * SchemaTablesWithFullTableScans generated by hbm2java
 */
public class SchemaTablesWithFullTableScans implements java.io.Serializable {

	private SchemaTablesWithFullTableScansId id;

	public SchemaTablesWithFullTableScans() {
	}

	public SchemaTablesWithFullTableScans(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

	public SchemaTablesWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(SchemaTablesWithFullTableScansId id) {
		this.id = id;
	}

}
