package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * StatementAnalysis generated by hbm2java
 */
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
