package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * UserSummary generated by hbm2java
 */
public class UserSummary implements java.io.Serializable {

	private UserSummaryId id;

	public UserSummary() {
	}

	public UserSummary(UserSummaryId id) {
		this.id = id;
	}

	public UserSummaryId getId() {
		return this.id;
	}

	public void setId(UserSummaryId id) {
		this.id = id;
	}

}
