package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * UserSummaryByFileIoType generated by hbm2java
 */
public class UserSummaryByFileIoType implements java.io.Serializable {

	private UserSummaryByFileIoTypeId id;

	public UserSummaryByFileIoType() {
	}

	public UserSummaryByFileIoType(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public UserSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
