package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * UserSummaryByFileIo generated by hbm2java
 */
public class UserSummaryByFileIo implements java.io.Serializable {

	private UserSummaryByFileIoId id;

	public UserSummaryByFileIo() {
	}

	public UserSummaryByFileIo(UserSummaryByFileIoId id) {
		this.id = id;
	}

	public UserSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoId id) {
		this.id = id;
	}

}
