package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * UserSummaryByStatementType generated by hbm2java
 */
public class UserSummaryByStatementType implements java.io.Serializable {

	private UserSummaryByStatementTypeId id;

	public UserSummaryByStatementType() {
	}

	public UserSummaryByStatementType(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

	public UserSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

}
