package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * WaitsByHostByLatency generated by hbm2java
 */
public class WaitsByHostByLatency implements java.io.Serializable {

	private WaitsByHostByLatencyId id;

	public WaitsByHostByLatency() {
	}

	public WaitsByHostByLatency(WaitsByHostByLatencyId id) {
		this.id = id;
	}

	public WaitsByHostByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByHostByLatencyId id) {
		this.id = id;
	}

}
