package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final

/**
 * WaitClassesGlobalByAvgLatency generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatency implements java.io.Serializable {

	private WaitClassesGlobalByAvgLatencyId id;

	public WaitClassesGlobalByAvgLatency() {
	}

	public WaitClassesGlobalByAvgLatency(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByAvgLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

}
