package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.hostSummaryByFileIoId;

/**
 * X.hostSummaryByFileIo generated by hbm2java
 */
public class X.hostSummaryByFileIo  implements java.io.Serializable {


     private X.hostSummaryByFileIoId id;

    public X.hostSummaryByFileIo() {
    }

    public X.hostSummaryByFileIo(X.hostSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoId id) {
        this.id = id;
    }




}


