package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.hostSummaryByStatementTypeId;

/**
 * X.hostSummaryByStatementType generated by hbm2java
 */
public class X.hostSummaryByStatementType  implements java.io.Serializable {


     private X.hostSummaryByStatementTypeId id;

    public X.hostSummaryByStatementType() {
    }

    public X.hostSummaryByStatementType(X.hostSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementTypeId id) {
        this.id = id;
    }




}


