package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.hostSummaryId;

/**
 * X.hostSummary generated by hbm2java
 */
public class X.hostSummary  implements java.io.Serializable {


     private X.hostSummaryId id;

    public X.hostSummary() {
    }

    public X.hostSummary(X.hostSummaryId id) {
       this.id = id;
    }
   
    public X.hostSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryId id) {
        this.id = id;
    }




}


