package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.hostSummaryByStatementLatencyId;

/**
 * X.hostSummaryByStatementLatency generated by hbm2java
 */
public class X.hostSummaryByStatementLatency  implements java.io.Serializable {


     private X.hostSummaryByStatementLatencyId id;

    public X.hostSummaryByStatementLatency() {
    }

    public X.hostSummaryByStatementLatency(X.hostSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


