package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.innodbLockWaitsId;

/**
 * X.innodbLockWaits generated by hbm2java
 */
public class X.innodbLockWaits  implements java.io.Serializable {


     private X.innodbLockWaitsId id;

    public X.innodbLockWaits() {
    }

    public X.innodbLockWaits(X.innodbLockWaitsId id) {
       this.id = id;
    }
   
    public X.innodbLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.innodbLockWaitsId id) {
        this.id = id;
    }




}


