package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.innodbBufferStatsByTableId;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


