package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.innodbBufferStatsBySchemaId;

/**
 * X.innodbBufferStatsBySchema generated by hbm2java
 */
public class X.innodbBufferStatsBySchema  implements java.io.Serializable {


     private X.innodbBufferStatsBySchemaId id;

    public X.innodbBufferStatsBySchema() {
    }

    public X.innodbBufferStatsBySchema(X.innodbBufferStatsBySchemaId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsBySchemaId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsBySchemaId id) {
        this.id = id;
    }




}


