package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.ioGlobalByWaitByLatencyId;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


