package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.ioByThreadByLatencyId;

/**
 * X.ioByThreadByLatency generated by hbm2java
 */
public class X.ioByThreadByLatency  implements java.io.Serializable {


     private X.ioByThreadByLatencyId id;

    public X.ioByThreadByLatency() {
    }

    public X.ioByThreadByLatency(X.ioByThreadByLatencyId id) {
       this.id = id;
    }
   
    public X.ioByThreadByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioByThreadByLatencyId id) {
        this.id = id;
    }




}


