package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.ioGlobalByWaitByBytesId;

/**
 * X.ioGlobalByWaitByBytes generated by hbm2java
 */
public class X.ioGlobalByWaitByBytes  implements java.io.Serializable {


     private X.ioGlobalByWaitByBytesId id;

    public X.ioGlobalByWaitByBytes() {
    }

    public X.ioGlobalByWaitByBytes(X.ioGlobalByWaitByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByBytesId id) {
        this.id = id;
    }




}


