package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.latestFileIoId;

/**
 * X.latestFileIo generated by hbm2java
 */
public class X.latestFileIo  implements java.io.Serializable {


     private X.latestFileIoId id;

    public X.latestFileIo() {
    }

    public X.latestFileIo(X.latestFileIoId id) {
       this.id = id;
    }
   
    public X.latestFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.latestFileIoId id) {
        this.id = id;
    }




}


