package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.memoryByUserByCurrentBytesId;

/**
 * X.memoryByUserByCurrentBytes generated by hbm2java
 */
public class X.memoryByUserByCurrentBytes  implements java.io.Serializable {


     private X.memoryByUserByCurrentBytesId id;

    public X.memoryByUserByCurrentBytes() {
    }

    public X.memoryByUserByCurrentBytes(X.memoryByUserByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByUserByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByUserByCurrentBytesId id) {
        this.id = id;
    }




}


