package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.memoryGlobalByCurrentBytesId;

/**
 * X.memoryGlobalByCurrentBytes generated by hbm2java
 */
public class X.memoryGlobalByCurrentBytes  implements java.io.Serializable {


     private X.memoryGlobalByCurrentBytesId id;

    public X.memoryGlobalByCurrentBytes() {
    }

    public X.memoryGlobalByCurrentBytes(X.memoryGlobalByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryGlobalByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryGlobalByCurrentBytesId id) {
        this.id = id;
    }




}


