package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.memoryByHostByCurrentBytesId;

/**
 * X.memoryByHostByCurrentBytes generated by hbm2java
 */
public class X.memoryByHostByCurrentBytes  implements java.io.Serializable {


     private X.memoryByHostByCurrentBytesId id;

    public X.memoryByHostByCurrentBytes() {
    }

    public X.memoryByHostByCurrentBytes(X.memoryByHostByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByHostByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByHostByCurrentBytesId id) {
        this.id = id;
    }




}


