package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.memoryByThreadByCurrentBytesId;

/**
 * X.memoryByThreadByCurrentBytes generated by hbm2java
 */
public class X.memoryByThreadByCurrentBytes  implements java.io.Serializable {


     private X.memoryByThreadByCurrentBytesId id;

    public X.memoryByThreadByCurrentBytes() {
    }

    public X.memoryByThreadByCurrentBytes(X.memoryByThreadByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByThreadByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByThreadByCurrentBytesId id) {
        this.id = id;
    }




}


