package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.processlistId;

/**
 * X.processlist generated by hbm2java
 */
public class X.processlist  implements java.io.Serializable {


     private X.processlistId id;

    public X.processlist() {
    }

    public X.processlist(X.processlistId id) {
       this.id = id;
    }
   
    public X.processlistId getId() {
        return this.id;
    }
    
    public void setId(X.processlistId id) {
        this.id = id;
    }




}


