package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.schemaTableStatisticsWithBufferId;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


