package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.schemaTablesWithFullTableScansId;

/**
 * X.schemaTablesWithFullTableScans generated by hbm2java
 */
public class X.schemaTablesWithFullTableScans  implements java.io.Serializable {


     private X.schemaTablesWithFullTableScansId id;

    public X.schemaTablesWithFullTableScans() {
    }

    public X.schemaTablesWithFullTableScans(X.schemaTablesWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.schemaTablesWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTablesWithFullTableScansId id) {
        this.id = id;
    }




}


