package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.schemaIndexStatisticsId;

/**
 * X.schemaIndexStatistics generated by hbm2java
 */
public class X.schemaIndexStatistics  implements java.io.Serializable {


     private X.schemaIndexStatisticsId id;

    public X.schemaIndexStatistics() {
    }

    public X.schemaIndexStatistics(X.schemaIndexStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaIndexStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaIndexStatisticsId id) {
        this.id = id;
    }




}


