package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.schemaFlattenedKeysId;

/**
 * X.schemaFlattenedKeys generated by hbm2java
 */
public class X.schemaFlattenedKeys  implements java.io.Serializable {


     private X.schemaFlattenedKeysId id;

    public X.schemaFlattenedKeys() {
    }

    public X.schemaFlattenedKeys(X.schemaFlattenedKeysId id) {
       this.id = id;
    }
   
    public X.schemaFlattenedKeysId getId() {
        return this.id;
    }
    
    public void setId(X.schemaFlattenedKeysId id) {
        this.id = id;
    }




}


