package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.schemaTableStatisticsId;

/**
 * X.schemaTableStatistics generated by hbm2java
 */
public class X.schemaTableStatistics  implements java.io.Serializable {


     private X.schemaTableStatisticsId id;

    public X.schemaTableStatistics() {
    }

    public X.schemaTableStatistics(X.schemaTableStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsId id) {
        this.id = id;
    }




}


