package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.sessionId;

/**
 * X.session generated by hbm2java
 */
public class X.session  implements java.io.Serializable {


     private X.sessionId id;

    public X.session() {
    }

    public X.session(X.sessionId id) {
       this.id = id;
    }
   
    public X.sessionId getId() {
        return this.id;
    }
    
    public void setId(X.sessionId id) {
        this.id = id;
    }




}


