package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.statementsWithTempTablesId;

/**
 * X.statementsWithTempTables generated by hbm2java
 */
public class X.statementsWithTempTables  implements java.io.Serializable {


     private X.statementsWithTempTablesId id;

    public X.statementsWithTempTables() {
    }

    public X.statementsWithTempTables(X.statementsWithTempTablesId id) {
       this.id = id;
    }
   
    public X.statementsWithTempTablesId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithTempTablesId id) {
        this.id = id;
    }




}


