package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.statementsWithErrorsOrWarningsId;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


