package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.userSummaryByStatementLatencyId;

/**
 * X.userSummaryByStatementLatency generated by hbm2java
 */
public class X.userSummaryByStatementLatency  implements java.io.Serializable {


     private X.userSummaryByStatementLatencyId id;

    public X.userSummaryByStatementLatency() {
    }

    public X.userSummaryByStatementLatency(X.userSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


