package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.userSummaryByFileIoId;

/**
 * X.userSummaryByFileIo generated by hbm2java
 */
public class X.userSummaryByFileIo  implements java.io.Serializable {


     private X.userSummaryByFileIoId id;

    public X.userSummaryByFileIo() {
    }

    public X.userSummaryByFileIo(X.userSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoId id) {
        this.id = id;
    }




}


