package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.userSummaryByStagesId;

/**
 * X.userSummaryByStages generated by hbm2java
 */
public class X.userSummaryByStages  implements java.io.Serializable {


     private X.userSummaryByStagesId id;

    public X.userSummaryByStages() {
    }

    public X.userSummaryByStages(X.userSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.userSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStagesId id) {
        this.id = id;
    }




}


