package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.userSummaryByStatementTypeId;

/**
 * X.userSummaryByStatementType generated by hbm2java
 */
public class X.userSummaryByStatementType  implements java.io.Serializable {


     private X.userSummaryByStatementTypeId id;

    public X.userSummaryByStatementType() {
    }

    public X.userSummaryByStatementType(X.userSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementTypeId id) {
        this.id = id;
    }




}


