package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.userSummaryId;

/**
 * X.userSummary generated by hbm2java
 */
public class X.userSummary  implements java.io.Serializable {


     private X.userSummaryId id;

    public X.userSummary() {
    }

    public X.userSummary(X.userSummaryId id) {
       this.id = id;
    }
   
    public X.userSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryId id) {
        this.id = id;
    }




}


