package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.waitClassesGlobalByAvgLatencyId;

/**
 * X.waitClassesGlobalByAvgLatency generated by hbm2java
 */
public class X.waitClassesGlobalByAvgLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByAvgLatencyId id;

    public X.waitClassesGlobalByAvgLatency() {
    }

    public X.waitClassesGlobalByAvgLatency(X.waitClassesGlobalByAvgLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByAvgLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByAvgLatencyId id) {
        this.id = id;
    }




}


