package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.waitClassesGlobalByLatencyId;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


