package com.bookstoredb.entity2;
// Generated Apr 1, 2021, 10:12:38 AM by Hibernate Tools 5.4.27.Final


import com.bookstoredb.entity2.X.waitsByUserByLatencyId;

/**
 * X.waitsByUserByLatency generated by hbm2java
 */
public class X.waitsByUserByLatency  implements java.io.Serializable {


     private X.waitsByUserByLatencyId id;

    public X.waitsByUserByLatency() {
    }

    public X.waitsByUserByLatency(X.waitsByUserByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByUserByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByUserByLatencyId id) {
        this.id = id;
    }




}


